name: Deploy TriviaSpark Demo to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prepare SQLite database for static data extraction
        run: |
          mkdir -p data
          export DATABASE_URL="file:./data/trivia.db"
          echo "DATABASE_URL=file:./data/trivia.db" >> $GITHUB_ENV

          # Try to create database and seed data if possible
          # If this fails, the extract-data script will use fallback data
          if npm run db:push 2>/dev/null; then
            echo "Database schema created successfully"
            if npm run seed:data-only 2>/dev/null; then
              echo "Database seeded with demo data"
            else
              echo "Database seeding failed, will use fallback data"
            fi
          else
            echo "Database creation failed, will use fallback data"
          fi

      - name: Build static site
        run: npm run build:static

      - name: Create 404.html for SPA routing
        run: cp ./docs/index.html ./docs/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
